version: '3.2'

# Criando Redes
networks:
  net-local:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.38.1.0/24

services:

#- Serviço Banco de Dados
    mysql:                                      
      build: 
        context: .
        dockerfile: ./Dockerfile/Dockerfile-mysql
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_PASSWORD=123456
        - MYSQL_DATABASE=database01
        - MYSQL_USER=db_user
      ports:
        - "3306:3306"
      volumes:
        - "./infra/mysql/db:/var/lib/mysql"
      networks:
        net-local:
          ipv4_address: 172.38.1.2
      extra_hosts:
          - "app01.local:172.38.1.5"
          - "app02.local:172.38.1.5"
          - "app03.local:172.38.1.5"

#- Serviço Gerenciamento Banco de Dados PHP-MYADMIN
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      links:
         - mysql:mysql
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
       - "8080:80"
      networks:
        net-local:
          ipv4_address: 172.38.1.3
      extra_hosts:
          - "app01.local:172.38.1.5"
          - "app02.local:172.38.1.5"
          - "app03.local:172.38.1.5"

#- Console de Comandos "artisan", "composer", "curl", "gulp", "bower" inclui serviço nodejs portas não configuradas.
    comandos:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-comandos
      container_name: comandos
      volumes:
       - "./dev:/var/www"
      restart: always
      networks:
        net-local:
          ipv4_address: 172.38.1.4
      extra_hosts:
          - "app01.local:172.38.1.5"
          - "app02.local:172.38.1.5"
          - "app03.local:172.38.1.5"

#- Serviço de Cache de Memória
    redis:
      container_name: redis
      image: redis:alpine
      restart: always
      ports:
       - "6379:6379"

#- Serviço Web Server (Nginx)
    web:
      image: nginx:latest
      container_name: web
      links:
        - mysql:mysql
        - redis:redis
        - php:php
        #- rabbitmq:rabbitmq
      environment:
        XDEBUG_CONFIG: "remote_host=172.38.1.5"
        PHP_IDE_CONFIG: "serverName=web"
      restart: always
      ports:
       - "80:80"
      volumes:
       - "./dev:/var/www"
       - "./infra/nginx/conf.d:/etc/nginx/conf.d"
      networks:
        net-local:
          ipv4_address: 172.38.1.5
      extra_hosts:
          - "app01.local:172.38.1.5"
          - "app02.local:172.38.1.5"
          - "app03.local:172.38.1.5"

#- Serviço de PHP-FPM 7
    php:
      build: 
        context: .
        dockerfile: Dockerfile/Dockerfile-phpfpm
      container_name: php    
      volumes:
       - "./dev:/var/www"
       - "./infra/php/php.ini:/usr/local/etc/php/php.ini"
      ports:
       - "9000:9000"
      networks:
        net-local:
          ipv4_address: 172.38.1.6
      extra_hosts:
          - "app01.local:172.38.1.5"
          - "app02.local:172.38.1.5"
          - "app03.local:172.38.1.5"


